listen_addresses = '*'
port = 5432
hba_file = '/etc/postgresql/pg_hba.conf'
password_encryption = 'scram-sha-256'
ssl = off
hot_standby = on
hot_standby_feedback = on
primary_slot_name = 'bigmac_fabric'
recovery_min_apply_delay = 0
wal_receiver_status_interval = '5s'
max_standby_streaming_delay = '30s'
restore_command = 'cp /var/backups/postgresql/%f %p'
track_commit_timestamp = on
log_connections = on
log_disconnections = on
shared_buffers = '256MB'
max_connections = 100
