import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Four sidebars, ordered by how much you already know.
 *
 * 1. `startHere`  — new, plain-English pages written for someone who has never
 *                   seen this system. No internal vocabulary before it is
 *                   defined.
 * 2. `handbook`   — the existing numbered pages, grouped by the job you are
 *                   trying to do rather than by page number.
 * 3. `reference`  — look-it-up material: commands, registries, atlas, feature
 *                   guides, design notes, examples, releases.
 * 4. `manual`     — the operating manual that ships inside an installed OS.
 *
 * Curated groups are hand-listed because the grouping is the judgement.
 * Directories that are already ordered by filename are `autogenerated`.
 */
const sidebars: SidebarsConfig = {
  startHere: [
    'docs/start/index',
    'docs/start/what-this-is',
    'docs/start/install',
    {
      type: 'category',
      label: 'The seven ideas',
      collapsed: false,
      items: [
        'docs/start/domains-and-projects',
        'docs/start/work-items',
        'docs/start/workflows',
        'docs/start/automations',
        'docs/start/runs-and-receipts',
        'docs/start/hosts',
        'docs/start/command-center',
      ],
    },
    'docs/start/glossary',
    'docs/start/where-to-go-next',
  ],

  handbook: [
    'docs/README',
    {
      type: 'category',
      label: 'Understand the system',
      collapsed: false,
      items: [
        'docs/00-overview',
        'docs/02-architecture',
        'docs/03-operating-model',
        'docs/04-information-architecture',
        'docs/25-source-of-truth',
      ],
    },
    {
      type: 'category',
      label: 'Install it and keep it healthy',
      items: [
        'docs/01-install-and-quickstart',
        'docs/14-config-update-backup',
        'docs/23-configuration-surfaces',
        'docs/16-health-doctor-validation',
        'docs/host-auto-doctor',
        'docs/18-troubleshooting-and-faq',
      ],
    },
    {
      type: 'category',
      label: 'Do the work',
      items: [
        'docs/06-workflows',
        'docs/37-governed-workflow-engine',
        'docs/08-runs-and-run-logs',
        'docs/07-automations',
        'docs/05-routing-and-context',
        'docs/26-adaptive-routing',
        'docs/30-context-contracts',
      ],
    },
    {
      type: 'category',
      label: 'Keep it running unattended',
      items: [
        'docs/09-runtime-and-always-on',
        'docs/10-events-and-chains',
        'docs/11-connected-sources',
        'docs/34-activity-analytics-ingestion',
        'docs/36-host-explorer-projection',
      ],
    },
    {
      type: 'category',
      label: 'Ship code with agents',
      items: [
        'docs/24-auto-dev-readiness',
        'docs/42-auto-dev-program',
        'docs/auto-dev-continuous-release',
        'docs/auto-dev-dep-updater',
        'docs/40-auto-dev-everything-maintainers',
        'docs/29-spec-engine',
        'docs/dependency-contract-tests',
        'docs/release-contract',
      ],
    },
    {
      type: 'category',
      label: 'Surfaces, apps and integrations',
      items: [
        'docs/13-agent-surfaces',
        'docs/29-agentic-os-gui',
        'docs/27-engineering-cockpit',
        'docs/31-claude-desktop-bridge',
        'docs/31-report-engine',
        'docs/12-control-plane-notion',
        'docs/28-doc-config-system',
      ],
    },
    {
      type: 'category',
      label: 'Build an OS for someone else',
      items: [
        'docs/15-customer-os-factory',
        'docs/19-factory-patterns',
        'docs/21-os-programs',
        'docs/20-os-cleanup-lifecycle',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [{type: 'autogenerated', dirName: 'docs/tutorials'}],
    },
  ],

  reference: [
    {
      type: 'category',
      label: 'Commands',
      collapsed: false,
      items: [
        'docs/17-cli-reference',
        'docs/22-cli-help-standard',
        'docs/architecture/command-reference',
      ],
    },
    {
      type: 'category',
      label: 'Resources, registries and rules',
      items: [
        'docs/39-first-class-resource-registry',
        'docs/32-registry-resource-authoring',
        'docs/33-filesystem-resource-lifecycle',
        'docs/38-operator-resource-query',
        'docs/35-effective-rule-hierarchy',
        'docs/29-versioned-object-library',
      ],
    },
    {
      type: 'category',
      label: 'Architecture atlas',
      items: [
        'docs/architecture/README',
        'docs/architecture/system-architecture',
        'docs/architecture/harness-modes',
        'docs/architecture/tool-catalog',
      ],
    },
    {
      type: 'category',
      label: 'Feature guides',
      items: [{type: 'autogenerated', dirName: 'docs/13-feature-guides'}],
    },
    {
      type: 'category',
      label: 'Design notes',
      items: [{type: 'autogenerated', dirName: 'docs/design-notes'}],
    },
    {
      type: 'category',
      label: 'Example OS trees',
      items: [{type: 'autogenerated', dirName: 'docs/examples'}],
    },
    {
      type: 'category',
      label: 'Release notes',
      items: [{type: 'autogenerated', dirName: 'docs/releases'}],
    },
    {
      type: 'category',
      label: 'QA records',
      items: [{type: 'autogenerated', dirName: 'docs/qa'}],
    },
    {
      type: 'category',
      label: 'Diagrams and assets',
      items: ['docs/diagrams/README', 'docs/assets/README'],
    },
  ],

  manual: [{type: 'autogenerated', dirName: 'operating-manual'}],
};

export default sidebars;
